export const START_DELETING_PROJECT = 'PROJECTS:START_DELETING_PROJECT';
export const SUCCESS_DELETING_PROJECT = 'PROJECTS:SUCCESS_DELETING_PROJECT';
export const FAIL_DELETING_PROJECT = 'PROJECTS:FAIL_DELETING_PROJECT';

export const RESET_STATE = 'PROJECTS:RESET_STATE';

export type Project = {
	id: string;
	projects: WebApi.Entities.Projects[];
};
